{% set name = "hpp-gui" %}
{% set version = "9.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8e4a030020f7c0876e74591797b805634a8ea572a2bcb619b5760872c5c5f508

build:
  number: 0
  skip: true  # [win or python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - omniorb                             # [build_platform != target_platform]
  host:
    - qt-main
    - libboost-headers
    - tinyxml
    - hpp-fcl
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - hpp-template-corba  {{ version }}
    - hpp-corbaserver  {{ version }}
    - hpp-manipulation-corba  {{ version }}
    - openscenegraph
    - openscenegraph-osgqt
    - gepetto-viewer
    - gepetto-viewer-corba
    - omniorb-libs
    - omniorb
    - omniorbpy
    - python
    - qhull
    - qhull-static
    - libgl-devel                         # [linux]
  run:
    - tinyxml
    - {{ pin_compatible('omniorb-libs', max_pin='x.x.x') }}
    - omniorb
    - omniorbpy
    - python
    - qhull
    - qhull-static

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/gepetto-gui-plugins/hppwidgetsplugin.so  # [unix]

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
